name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SEU_USUARIO

          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: America/Bahia

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

          plugin_isocalendar: yes
          plugin_stars: yes
